---
- name: Play to Run MAven Build
  hosts: Build_Hosts 
  connection: local
  gather_facts: false
  tasks:
    - name: Task to Running MAVEN Build
      shell: 
             cd trucks; mvn -T 4 '{{ item }}'
       

      loop: 
             - validate
             - compile
             - test
             - package
             - verify
